// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InboxMessage struct {
	Recipient string
	ID        int64
	Created   pgtype.Timestamptz
	CreatedBy string
	Updated   pgtype.Timestamptz
	Payload   []byte
}

type Message struct {
	Recipient string
	ID        int64
	Type      pgtype.Text
	Created   pgtype.Timestamptz
	CreatedBy string
	DocUuid   pgtype.UUID
	DocType   pgtype.Text
	Payload   []byte
}

type MessageWriteLock struct {
	Recipient        string
	MessageType      string
	CurrentMessageID pgtype.Int8
}

type SchemaVersion struct {
	Version int32
}
