// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateConfigGeneration = `-- name: ActivateConfigGeneration :exec
UPDATE config_generation SET active = true, activated_at = now()
WHERE id = $1
`

func (q *Queries) ActivateConfigGeneration(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, activateConfigGeneration, id)
	return err
}

const deactivateActiveConfigGeneration = `-- name: DeactivateActiveConfigGeneration :exec
UPDATE config_generation SET active = false
WHERE active AND id != $1
`

func (q *Queries) DeactivateActiveConfigGeneration(ctx context.Context, excludeID int64) error {
	_, err := q.db.Exec(ctx, deactivateActiveConfigGeneration, excludeID)
	return err
}

const deleteDocument = `-- name: DeleteDocument :one
DELETE FROM document
WHERE owner = $1
      AND application = $2
      AND type = $3
      AND key = $4
RETURNING 1
`

type DeleteDocumentParams struct {
	Owner       string
	Application string
	Type        string
	Key         string
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteDocument,
		arg.Owner,
		arg.Application,
		arg.Type,
		arg.Key,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteOldInboxMessages = `-- name: DeleteOldInboxMessages :exec
DELETE FROM inbox_message
WHERE created < now() - INTERVAL '6 months'
`

func (q *Queries) DeleteOldInboxMessages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldInboxMessages)
	return err
}

const deleteOldMessages = `-- name: DeleteOldMessages :exec
DELETE FROM message
WHERE created < now() - INTERVAL '2 weeks'
`

func (q *Queries) DeleteOldMessages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldMessages)
	return err
}

const deleteProperty = `-- name: DeleteProperty :one
DELETE FROM property
WHERE owner = $1
      AND application = $2
      AND key = $3
RETURNING 1
`

type DeletePropertyParams struct {
	Owner       string
	Application string
	Key         string
}

func (q *Queries) DeleteProperty(ctx context.Context, arg DeletePropertyParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteProperty, arg.Owner, arg.Application, arg.Key)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const ensureSchema = `-- name: EnsureSchema :exec
INSERT INTO document_schema (name, version, spec, usage)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name, version) DO NOTHING
`

type EnsureSchemaParams struct {
	Name    string
	Version string
	Spec    []byte
	Usage   SchemaUsage
}

func (q *Queries) EnsureSchema(ctx context.Context, arg EnsureSchemaParams) error {
	_, err := q.db.Exec(ctx, ensureSchema,
		arg.Name,
		arg.Version,
		arg.Spec,
		arg.Usage,
	)
	return err
}

const getActiveConfigGeneration = `-- name: GetActiveConfigGeneration :one
SELECT id, identity_hash, description, created_at, activated_at, active
FROM config_generation
WHERE active
`

func (q *Queries) GetActiveConfigGeneration(ctx context.Context) (ConfigGeneration, error) {
	row := q.db.QueryRow(ctx, getActiveConfigGeneration)
	var i ConfigGeneration
	err := row.Scan(
		&i.ID,
		&i.IdentityHash,
		&i.Description,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.Active,
	)
	return i, err
}

const getActiveSchema = `-- name: GetActiveSchema :one
SELECT ds.name, ds.version, ds.spec, ds.usage
FROM config_generation AS cg
     INNER JOIN config_generation_schema AS cgs
           ON cgs.generation_id = cg.id
     INNER JOIN document_schema AS ds
           ON ds.name = cgs.name AND ds.version = cgs.version
WHERE cg.active AND cgs.name = $1
`

func (q *Queries) GetActiveSchema(ctx context.Context, name string) (DocumentSchema, error) {
	row := q.db.QueryRow(ctx, getActiveSchema, name)
	var i DocumentSchema
	err := row.Scan(
		&i.Name,
		&i.Version,
		&i.Spec,
		&i.Usage,
	)
	return i, err
}

const getActiveSchemas = `-- name: GetActiveSchemas :many
SELECT cgs.name, cgs.version, ds.spec, ds.usage
FROM config_generation AS cg
     INNER JOIN config_generation_schema AS cgs
           ON cgs.generation_id = cg.id
     INNER JOIN document_schema AS ds
           ON ds.name = cgs.name AND ds.version = cgs.version
WHERE cg.active
ORDER BY cgs.ordinal
`

type GetActiveSchemasRow struct {
	Name    string
	Version string
	Spec    []byte
	Usage   SchemaUsage
}

func (q *Queries) GetActiveSchemas(ctx context.Context) ([]GetActiveSchemasRow, error) {
	rows, err := q.db.Query(ctx, getActiveSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveSchemasRow
	for rows.Next() {
		var i GetActiveSchemasRow
		if err := rows.Scan(
			&i.Name,
			&i.Version,
			&i.Spec,
			&i.Usage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfigGeneration = `-- name: GetConfigGeneration :one
SELECT id, identity_hash, description, created_at, activated_at, active
FROM config_generation
WHERE id = $1
`

func (q *Queries) GetConfigGeneration(ctx context.Context, id int64) (ConfigGeneration, error) {
	row := q.db.QueryRow(ctx, getConfigGeneration, id)
	var i ConfigGeneration
	err := row.Scan(
		&i.ID,
		&i.IdentityHash,
		&i.Description,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.Active,
	)
	return i, err
}

const getConfigGenerationByIdentityHash = `-- name: GetConfigGenerationByIdentityHash :one
SELECT id, identity_hash, description, created_at, activated_at, active
FROM config_generation
WHERE identity_hash = $1
`

func (q *Queries) GetConfigGenerationByIdentityHash(ctx context.Context, identityHash string) (ConfigGeneration, error) {
	row := q.db.QueryRow(ctx, getConfigGenerationByIdentityHash, identityHash)
	var i ConfigGeneration
	err := row.Scan(
		&i.ID,
		&i.IdentityHash,
		&i.Description,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.Active,
	)
	return i, err
}

const getConfigGenerationSchemas = `-- name: GetConfigGenerationSchemas :many
SELECT cgs.name, cgs.version, ds.usage
FROM config_generation_schema AS cgs
     INNER JOIN document_schema AS ds
           ON ds.name = cgs.name AND ds.version = cgs.version
WHERE cgs.generation_id = $1
ORDER BY cgs.ordinal
`

type GetConfigGenerationSchemasRow struct {
	Name    string
	Version string
	Usage   SchemaUsage
}

func (q *Queries) GetConfigGenerationSchemas(ctx context.Context, generationID int64) ([]GetConfigGenerationSchemasRow, error) {
	rows, err := q.db.Query(ctx, getConfigGenerationSchemas, generationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConfigGenerationSchemasRow
	for rows.Next() {
		var i GetConfigGenerationSchemasRow
		if err := rows.Scan(&i.Name, &i.Version, &i.Usage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfigGenerationSchemasWithSpec = `-- name: GetConfigGenerationSchemasWithSpec :many
SELECT cgs.name, cgs.version, ds.spec, ds.usage
FROM config_generation_schema AS cgs
     INNER JOIN document_schema AS ds
           ON ds.name = cgs.name AND ds.version = cgs.version
WHERE cgs.generation_id = $1
ORDER BY cgs.ordinal
`

type GetConfigGenerationSchemasWithSpecRow struct {
	Name    string
	Version string
	Spec    []byte
	Usage   SchemaUsage
}

func (q *Queries) GetConfigGenerationSchemasWithSpec(ctx context.Context, generationID int64) ([]GetConfigGenerationSchemasWithSpecRow, error) {
	rows, err := q.db.Query(ctx, getConfigGenerationSchemasWithSpec, generationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConfigGenerationSchemasWithSpecRow
	for rows.Next() {
		var i GetConfigGenerationSchemasWithSpecRow
		if err := rows.Scan(
			&i.Name,
			&i.Version,
			&i.Spec,
			&i.Usage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeprecations = `-- name: GetDeprecations :many
SELECT label, enforced
FROM deprecation
ORDER BY label
`

func (q *Queries) GetDeprecations(ctx context.Context) ([]Deprecation, error) {
	rows, err := q.db.Query(ctx, getDeprecations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deprecation
	for rows.Next() {
		var i Deprecation
		if err := rows.Scan(&i.Label, &i.Enforced); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocument = `-- name: GetDocument :one
SELECT owner, application, type, key, version, schema_version,
       title, created, updated, updated_by, payload
FROM document
WHERE owner = $1
      AND application = $2
      AND type = $3
      AND key = $4
`

type GetDocumentParams struct {
	Owner       string
	Application string
	Type        string
	Key         string
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument,
		arg.Owner,
		arg.Application,
		arg.Type,
		arg.Key,
	)
	var i Document
	err := row.Scan(
		&i.Owner,
		&i.Application,
		&i.Type,
		&i.Key,
		&i.Version,
		&i.SchemaVersion,
		&i.Title,
		&i.Created,
		&i.Updated,
		&i.UpdatedBy,
		&i.Payload,
	)
	return i, err
}

const getEnforcedDeprecations = `-- name: GetEnforcedDeprecations :many
SELECT label
FROM deprecation
WHERE enforced
`

func (q *Queries) GetEnforcedDeprecations(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getEnforcedDeprecations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventLogEntriesAfterId = `-- name: GetEventLogEntriesAfterId :many
SELECT id, owner, type, resource_kind, application, document_type,
       key, version, updated_by, created, payload
FROM eventlog
WHERE owner = ANY($1::text[])
      AND id > $2
ORDER BY id ASC
LIMIT $3::bigint
`

type GetEventLogEntriesAfterIdParams struct {
	Owners  []string
	AfterID int64
	Limit   int64
}

func (q *Queries) GetEventLogEntriesAfterId(ctx context.Context, arg GetEventLogEntriesAfterIdParams) ([]Eventlog, error) {
	rows, err := q.db.Query(ctx, getEventLogEntriesAfterId, arg.Owners, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Eventlog
	for rows.Next() {
		var i Eventlog
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Type,
			&i.ResourceKind,
			&i.Application,
			&i.DocumentType,
			&i.Key,
			&i.Version,
			&i.UpdatedBy,
			&i.Created,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInboxMessageByUUID = `-- name: GetInboxMessageByUUID :one
SELECT id, (payload = $1::jsonb)::bool AS same_payload
FROM inbox_message
WHERE recipient = $2
      AND uuid = $3
`

type GetInboxMessageByUUIDParams struct {
	Payload   []byte
	Recipient string
	UUID      uuid.UUID
}

type GetInboxMessageByUUIDRow struct {
	ID          int64
	SamePayload bool
}

func (q *Queries) GetInboxMessageByUUID(ctx context.Context, arg GetInboxMessageByUUIDParams) (GetInboxMessageByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getInboxMessageByUUID, arg.Payload, arg.Recipient, arg.UUID)
	var i GetInboxMessageByUUIDRow
	err := row.Scan(&i.ID, &i.SamePayload)
	return i, err
}

const getInboxMessageForReader = `-- name: GetInboxMessageForReader :one
SELECT id, recipient, created_by
FROM inbox_message
WHERE id = $1
      AND recipient = ANY($2::text[])
`

type GetInboxMessageForReaderParams struct {
	ID     int64
	Owners []string
}

type GetInboxMessageForReaderRow struct {
	ID        int64
	Recipient string
	CreatedBy string
}

func (q *Queries) GetInboxMessageForReader(ctx context.Context, arg GetInboxMessageForReaderParams) (GetInboxMessageForReaderRow, error) {
	row := q.db.QueryRow(ctx, getInboxMessageForReader, arg.ID, arg.Owners)
	var i GetInboxMessageForReaderRow
	err := row.Scan(&i.ID, &i.Recipient, &i.CreatedBy)
	return i, err
}

const getLatestEventLogId = `-- name: GetLatestEventLogId :one
SELECT COALESCE(MAX(id), 0)::bigint
FROM eventlog
WHERE owner = ANY($1::text[])
`

func (q *Queries) GetLatestEventLogId(ctx context.Context, owners []string) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestEventLogId, owners)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getLatestInboxMessageId = `-- name: GetLatestInboxMessageId :one
SELECT COALESCE(MAX(id), 0)::bigint AS latest_id
FROM inbox_message
WHERE recipient = ANY($1::text[])
`

func (q *Queries) GetLatestInboxMessageId(ctx context.Context, owners []string) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestInboxMessageId, owners)
	var latest_id int64
	err := row.Scan(&latest_id)
	return latest_id, err
}

const getLatestMessageId = `-- name: GetLatestMessageId :one
SELECT COALESCE(MAX(id), 0)::bigint AS latest_id
FROM message
WHERE recipient = $1
`

func (q *Queries) GetLatestMessageId(ctx context.Context, recipient string) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestMessageId, recipient)
	var latest_id int64
	err := row.Scan(&latest_id)
	return latest_id, err
}

const getProperties = `-- name: GetProperties :many
SELECT owner, application, key, value, created, updated
FROM property
WHERE owner = $1
      AND ($2::text IS NULL OR application = $2::text)
      AND ($3::text[] IS NULL OR key = ANY($3::text[]))
`

type GetPropertiesParams struct {
	Owner       string
	Application pgtype.Text
	Keys        []string
}

func (q *Queries) GetProperties(ctx context.Context, arg GetPropertiesParams) ([]Property, error) {
	rows, err := q.db.Query(ctx, getProperties, arg.Owner, arg.Application, arg.Keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Property
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.Owner,
			&i.Application,
			&i.Key,
			&i.Value,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSchema = `-- name: GetSchema :one
SELECT name, version, spec, usage
FROM document_schema
WHERE name = $1 AND version = $2
`

type GetSchemaParams struct {
	Name    string
	Version string
}

func (q *Queries) GetSchema(ctx context.Context, arg GetSchemaParams) (DocumentSchema, error) {
	row := q.db.QueryRow(ctx, getSchema, arg.Name, arg.Version)
	var i DocumentSchema
	err := row.Scan(
		&i.Name,
		&i.Version,
		&i.Spec,
		&i.Usage,
	)
	return i, err
}

const hideInboxMessage = `-- name: HideInboxMessage :exec
INSERT INTO inbox_message_state (message_id, subject, is_read, hidden, updated)
VALUES ($1, $2, false, true, $3)
ON CONFLICT (message_id, subject) DO UPDATE
SET hidden = true,
    updated = EXCLUDED.updated
`

type HideInboxMessageParams struct {
	MessageID int64
	Subject   string
	Updated   pgtype.Timestamptz
}

func (q *Queries) HideInboxMessage(ctx context.Context, arg HideInboxMessageParams) error {
	_, err := q.db.Exec(ctx, hideInboxMessage, arg.MessageID, arg.Subject, arg.Updated)
	return err
}

const insertConfigGeneration = `-- name: InsertConfigGeneration :one
INSERT INTO config_generation (identity_hash, description)
VALUES ($1, $2)
RETURNING id, identity_hash, description, created_at, activated_at, active
`

type InsertConfigGenerationParams struct {
	IdentityHash string
	Description  string
}

func (q *Queries) InsertConfigGeneration(ctx context.Context, arg InsertConfigGenerationParams) (ConfigGeneration, error) {
	row := q.db.QueryRow(ctx, insertConfigGeneration, arg.IdentityHash, arg.Description)
	var i ConfigGeneration
	err := row.Scan(
		&i.ID,
		&i.IdentityHash,
		&i.Description,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.Active,
	)
	return i, err
}

const insertConfigGenerationSchema = `-- name: InsertConfigGenerationSchema :exec
INSERT INTO config_generation_schema (generation_id, name, version, ordinal)
VALUES ($1, $2, $3, $4)
`

type InsertConfigGenerationSchemaParams struct {
	GenerationID int64
	Name         string
	Version      string
	Ordinal      int32
}

func (q *Queries) InsertConfigGenerationSchema(ctx context.Context, arg InsertConfigGenerationSchemaParams) error {
	_, err := q.db.Exec(ctx, insertConfigGenerationSchema,
		arg.GenerationID,
		arg.Name,
		arg.Version,
		arg.Ordinal,
	)
	return err
}

const insertEventLog = `-- name: InsertEventLog :exec
INSERT INTO eventlog (
      id, owner, type, resource_kind, application, document_type,
      key, version, updated_by, created, payload
) VALUES (
      $1,
      $2,
      $3, -- type (update/delete)
      $4, -- resource_kind (document/property)
      $5,
      $6, -- empty if resource_kind is 'property'
      $7,
      $8,
      $9,
      $10,
      $11
)
`

type InsertEventLogParams struct {
	ID           int64
	Owner        string
	Type         EventType
	ResourceKind ResourceKind
	Application  string
	DocumentType pgtype.Text
	Key          string
	Version      pgtype.Int8
	UpdatedBy    string
	Created      pgtype.Timestamptz
	Payload      []byte
}

func (q *Queries) InsertEventLog(ctx context.Context, arg InsertEventLogParams) error {
	_, err := q.db.Exec(ctx, insertEventLog,
		arg.ID,
		arg.Owner,
		arg.Type,
		arg.ResourceKind,
		arg.Application,
		arg.DocumentType,
		arg.Key,
		arg.Version,
		arg.UpdatedBy,
		arg.Created,
		arg.Payload,
	)
	return err
}

const insertInboxMessage = `-- name: InsertInboxMessage :exec
INSERT INTO inbox_message(
      id, uuid, recipient, created, created_by, payload
) VALUES (
      $1, $2, $3, $4, $5, $6
)
`

type InsertInboxMessageParams struct {
	ID        int64
	UUID      uuid.UUID
	Recipient string
	Created   pgtype.Timestamptz
	CreatedBy string
	Payload   []byte
}

func (q *Queries) InsertInboxMessage(ctx context.Context, arg InsertInboxMessageParams) error {
	_, err := q.db.Exec(ctx, insertInboxMessage,
		arg.ID,
		arg.UUID,
		arg.Recipient,
		arg.Created,
		arg.CreatedBy,
		arg.Payload,
	)
	return err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO message(
      recipient, id, type, created, created_by, doc_uuid, doc_type, payload
) VALUES (
      $1, $2, $3, $4, $5, $6, $7, $8
)
`

type InsertMessageParams struct {
	Recipient string
	ID        int64
	Type      pgtype.Text
	Created   pgtype.Timestamptz
	CreatedBy string
	DocUuid   pgtype.UUID
	DocType   pgtype.Text
	Payload   []byte
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.Recipient,
		arg.ID,
		arg.Type,
		arg.Created,
		arg.CreatedBy,
		arg.DocUuid,
		arg.DocType,
		arg.Payload,
	)
	return err
}

const listConfigGenerations = `-- name: ListConfigGenerations :many
SELECT id, identity_hash, description, created_at, activated_at, active
FROM config_generation
WHERE ($1::bigint = 0 OR id < $1::bigint)
ORDER BY id DESC
LIMIT $2::bigint
`

type ListConfigGenerationsParams struct {
	Before   int64
	PageSize int64
}

func (q *Queries) ListConfigGenerations(ctx context.Context, arg ListConfigGenerationsParams) ([]ConfigGeneration, error) {
	rows, err := q.db.Query(ctx, listConfigGenerations, arg.Before, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigGeneration
	for rows.Next() {
		var i ConfigGeneration
		if err := rows.Scan(
			&i.ID,
			&i.IdentityHash,
			&i.Description,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsFull = `-- name: ListDocumentsFull :many
SELECT owner, application, type, key, version, schema_version,
       title, created, updated, updated_by, payload
FROM document
WHERE owner = ANY($1::text[])
      AND ($2::text IS NULL OR application = $2::text)
      AND ($3::text IS NULL OR type = $3::text)
ORDER BY application ASC, type ASC, key ASC
`

type ListDocumentsFullParams struct {
	Owners      []string
	Application pgtype.Text
	Type        pgtype.Text
}

func (q *Queries) ListDocumentsFull(ctx context.Context, arg ListDocumentsFullParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsFull, arg.Owners, arg.Application, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.Owner,
			&i.Application,
			&i.Type,
			&i.Key,
			&i.Version,
			&i.SchemaVersion,
			&i.Title,
			&i.Created,
			&i.Updated,
			&i.UpdatedBy,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsMetadata = `-- name: ListDocumentsMetadata :many
SELECT owner, application, type, key, version, schema_version,
       title, created, updated, updated_by
FROM document
WHERE owner = ANY($1::text[])
      AND ($2::text IS NULL OR application = $2::text)
      AND ($3::text IS NULL OR type = $3::text)
ORDER BY application ASC, type ASC, key ASC
`

type ListDocumentsMetadataParams struct {
	Owners      []string
	Application pgtype.Text
	Type        pgtype.Text
}

type ListDocumentsMetadataRow struct {
	Owner         string
	Application   string
	Type          string
	Key           string
	Version       int64
	SchemaVersion string
	Title         string
	Created       pgtype.Timestamptz
	Updated       pgtype.Timestamptz
	UpdatedBy     string
}

func (q *Queries) ListDocumentsMetadata(ctx context.Context, arg ListDocumentsMetadataParams) ([]ListDocumentsMetadataRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsMetadata, arg.Owners, arg.Application, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsMetadataRow
	for rows.Next() {
		var i ListDocumentsMetadataRow
		if err := rows.Scan(
			&i.Owner,
			&i.Application,
			&i.Type,
			&i.Key,
			&i.Version,
			&i.SchemaVersion,
			&i.Title,
			&i.Created,
			&i.Updated,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxMessagesAfterId = `-- name: ListInboxMessagesAfterId :many
SELECT m.id, m.uuid, m.recipient, m.created, m.created_by, m.payload,
       COALESCE(s.is_read, false)::bool AS is_read
FROM inbox_message AS m
     LEFT JOIN inbox_message_state AS s
       ON s.message_id = m.id AND s.subject = $1
WHERE m.recipient = ANY($2::text[])
      AND m.id > $3
      AND NOT COALESCE(s.hidden, false)
ORDER BY m.id ASC
LIMIT $4::bigint
`

type ListInboxMessagesAfterIdParams struct {
	Subject string
	Owners  []string
	AfterID int64
	Limit   int64
}

type ListInboxMessagesAfterIdRow struct {
	ID        int64
	UUID      uuid.UUID
	Recipient string
	Created   pgtype.Timestamptz
	CreatedBy string
	Payload   []byte
	IsRead    bool
}

func (q *Queries) ListInboxMessagesAfterId(ctx context.Context, arg ListInboxMessagesAfterIdParams) ([]ListInboxMessagesAfterIdRow, error) {
	rows, err := q.db.Query(ctx, listInboxMessagesAfterId,
		arg.Subject,
		arg.Owners,
		arg.AfterID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboxMessagesAfterIdRow
	for rows.Next() {
		var i ListInboxMessagesAfterIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UUID,
			&i.Recipient,
			&i.Created,
			&i.CreatedBy,
			&i.Payload,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxMessagesBeforeId = `-- name: ListInboxMessagesBeforeId :many
SELECT m.id, m.uuid, m.recipient, m.created, m.created_by, m.payload,
       COALESCE(s.is_read, false)::bool AS is_read
FROM inbox_message AS m
     LEFT JOIN inbox_message_state AS s
       ON s.message_id = m.id AND s.subject = $1
WHERE m.recipient = ANY($2::text[])
      AND ($3::bigint = 0 OR m.id < $3)
      AND NOT COALESCE(s.hidden, false)
ORDER BY m.id DESC
LIMIT $4::bigint
`

type ListInboxMessagesBeforeIdParams struct {
	Subject  string
	Owners   []string
	BeforeID int64
	Limit    int64
}

type ListInboxMessagesBeforeIdRow struct {
	ID        int64
	UUID      uuid.UUID
	Recipient string
	Created   pgtype.Timestamptz
	CreatedBy string
	Payload   []byte
	IsRead    bool
}

func (q *Queries) ListInboxMessagesBeforeId(ctx context.Context, arg ListInboxMessagesBeforeIdParams) ([]ListInboxMessagesBeforeIdRow, error) {
	rows, err := q.db.Query(ctx, listInboxMessagesBeforeId,
		arg.Subject,
		arg.Owners,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboxMessagesBeforeIdRow
	for rows.Next() {
		var i ListInboxMessagesBeforeIdRow
		if err := rows.Scan(
			&i.ID,
			&i.UUID,
			&i.Recipient,
			&i.Created,
			&i.CreatedBy,
			&i.Payload,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfterId = `-- name: ListMessagesAfterId :many
SELECT recipient, id, type, created, created_by, doc_uuid, doc_type, payload
FROM message
WHERE recipient = $1
      AND id > $2
ORDER BY id ASC
LIMIT $3::bigint
`

type ListMessagesAfterIdParams struct {
	Recipient string
	AfterID   int64
	Limit     int64
}

func (q *Queries) ListMessagesAfterId(ctx context.Context, arg ListMessagesAfterIdParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesAfterId, arg.Recipient, arg.AfterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.Recipient,
			&i.ID,
			&i.Type,
			&i.Created,
			&i.CreatedBy,
			&i.DocUuid,
			&i.DocType,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMessageID = `-- name: NextMessageID :one
INSERT INTO message_write_lock(
      recipient, message_type, current_message_id
) VALUES (
      $1, $2, 1
)
ON CONFLICT(recipient, message_type)
DO UPDATE SET
  current_message_id = message_write_lock.current_message_id + 1
RETURNING current_message_id
`

type NextMessageIDParams struct {
	Recipient   string
	MessageType string
}

func (q *Queries) NextMessageID(ctx context.Context, arg NextMessageIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextMessageID, arg.Recipient, arg.MessageType)
	var current_message_id int64
	err := row.Scan(&current_message_id)
	return current_message_id, err
}

const notify = `-- name: Notify :exec
SELECT pg_notify($1::text, $2::text)
`

type NotifyParams struct {
	Channel string
	Message string
}

func (q *Queries) Notify(ctx context.Context, arg NotifyParams) error {
	_, err := q.db.Exec(ctx, notify, arg.Channel, arg.Message)
	return err
}

const reserveSequenceValues = `-- name: ReserveSequenceValues :one
UPDATE sequence_counter
SET value = value + $1::bigint
WHERE name = $2
RETURNING value
`

type ReserveSequenceValuesParams struct {
	Count int64
	Name  string
}

func (q *Queries) ReserveSequenceValues(ctx context.Context, arg ReserveSequenceValuesParams) (int64, error) {
	row := q.db.QueryRow(ctx, reserveSequenceValues, arg.Count, arg.Name)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const setInboxMessageRead = `-- name: SetInboxMessageRead :exec
INSERT INTO inbox_message_state (message_id, subject, is_read, hidden, updated)
VALUES ($1, $2, $3, false, $4)
ON CONFLICT (message_id, subject) DO UPDATE
SET is_read = EXCLUDED.is_read,
    updated = EXCLUDED.updated
`

type SetInboxMessageReadParams struct {
	MessageID int64
	Subject   string
	IsRead    bool
	Updated   pgtype.Timestamptz
}

func (q *Queries) SetInboxMessageRead(ctx context.Context, arg SetInboxMessageReadParams) error {
	_, err := q.db.Exec(ctx, setInboxMessageRead,
		arg.MessageID,
		arg.Subject,
		arg.IsRead,
		arg.Updated,
	)
	return err
}

const upsertDeprecation = `-- name: UpsertDeprecation :exec
INSERT INTO deprecation (label, enforced)
VALUES ($1, $2)
ON CONFLICT (label) DO UPDATE SET enforced = excluded.enforced
`

type UpsertDeprecationParams struct {
	Label    string
	Enforced bool
}

func (q *Queries) UpsertDeprecation(ctx context.Context, arg UpsertDeprecationParams) error {
	_, err := q.db.Exec(ctx, upsertDeprecation, arg.Label, arg.Enforced)
	return err
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO document (
      owner, application, type, key,
      version, schema_version, title, created,
      updated, updated_by, payload
) VALUES (
      $1, $2, $3, $4,
      1, $5, $6, now(),
      now(), $7, $8
)
ON CONFLICT (owner, application, type, key)
DO UPDATE SET
  version = document.version + 1,
  schema_version = EXCLUDED.schema_version,
  title = EXCLUDED.title,
  updated_by = EXCLUDED.updated_by,
  updated = now(),
  payload = EXCLUDED.payload
RETURNING version
`

type UpsertDocumentParams struct {
	Owner         string
	Application   string
	Type          string
	Key           string
	SchemaVersion string
	Title         string
	UpdatedBy     string
	Payload       []byte
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertDocument,
		arg.Owner,
		arg.Application,
		arg.Type,
		arg.Key,
		arg.SchemaVersion,
		arg.Title,
		arg.UpdatedBy,
		arg.Payload,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const upsertProperty = `-- name: UpsertProperty :exec
INSERT INTO property (
      owner, application, key, value, updated
) VALUES (
      $1, $2, $3, $4, now()
)
ON CONFLICT (owner, application, key)
DO UPDATE SET
  value = EXCLUDED.value,
  updated = now()
`

type UpsertPropertyParams struct {
	Owner       string
	Application string
	Key         string
	Value       string
}

func (q *Queries) UpsertProperty(ctx context.Context, arg UpsertPropertyParams) error {
	_, err := q.db.Exec(ctx, upsertProperty,
		arg.Owner,
		arg.Application,
		arg.Key,
		arg.Value,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO "user"(
      sub, created, kind
) VALUES (
      $1, $2, $3
)
ON CONFLICT (sub)
DO NOTHING
`

type UpsertUserParams struct {
	Sub     string
	Created pgtype.Timestamptz
	Kind    UserKind
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser, arg.Sub, arg.Created, arg.Kind)
	return err
}
